import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import './TransportOperationsFixed.css'

const EMPTY={kendaraan_id:'',jenis_dokumen:'STNK',nomor_dokumen:'',tanggal_terbit:'',tanggal_berlaku_mulai:'',tanggal_jatuh_tempo:'',keterangan:''}
const fmt=v=>v?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'}).format(new Date(v)):'-'
const Alert=({type='success',children})=><div className={`x-alert ${type}`}>{children}</div>

export default function DocumentsFeaturePage({profile}){
 const [docs,setDocs]=useState([]),[vehicles,setVehicles]=useState([]),[form,setForm]=useState(EMPTY),[file,setFile]=useState(null)
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const [editing,setEditing]=useState(null),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState('SEMUA')
 const canManage=['ADMIN','TRANSPORT'].includes(profile?.role)
 const vehicleMap=useMemo(()=>Object.fromEntries(vehicles.map(v=>[v.id,v])),[vehicles])
 const load=async()=>{setLoading(true);setError('');const [d,v]=await Promise.all([supabase.from('dokumen_kendaraan').select('*').order('tanggal_jatuh_tempo',{ascending:true}),supabase.from('kendaraan').select('id,nomor_polisi,merk,tipe').order('nomor_polisi')]);if(d.error)setError(`Dokumen: ${d.error.message}`);if(v.error)setError(e=>e||`Kendaraan: ${v.error.message}`);setDocs(d.data||[]);setVehicles(v.data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return docs.filter(d=>{const days=d.tanggal_jatuh_tempo?Math.ceil((new Date(d.tanggal_jatuh_tempo)-new Date())/86400000):null;const status=days===null?'TANPA_TANGGAL':days<0?'EXPIRED':days<=30?'SEGERA':'AMAN';const text=[d.jenis_dokumen,d.nomor_dokumen,d.keterangan,vehicleMap[d.kendaraan_id]?.nomor_polisi,vehicleMap[d.kendaraan_id]?.merk].filter(Boolean).join(' ').toLowerCase();return (!q||text.includes(q))&&(statusFilter==='SEMUA'||status===statusFilter)})},[docs,vehicleMap,query,statusFilter])
 const resetForm=()=>{setForm(EMPTY);setFile(null);setEditing(null)}
 const save=async e=>{e.preventDefault();if(!canManage)return;if(!form.kendaraan_id||!form.tanggal_jatuh_tempo){setError('Kendaraan dan tanggal jatuh tempo wajib diisi.');return}setSaving(true);setError('');setSuccess('');try{let path=editing?.file_path||null;if(file){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');path=`${form.kendaraan_id}/${Date.now()}-${crypto.randomUUID()}-${safe}`;const {error}=await supabase.storage.from('dokumen-kendaraan').upload(path,file,{upsert:false,contentType:file.type||undefined});if(error)throw error}
  const payload={...form,kendaraan_id:Number(form.kendaraan_id),file_path:path}
  const result=editing?await supabase.from('dokumen_kendaraan').update(payload).eq('id',editing.id):await supabase.from('dokumen_kendaraan').insert(payload)
  if(result.error)throw result.error
  if(editing&&file&&editing.file_path)await supabase.storage.from('dokumen-kendaraan').remove([editing.file_path])
  resetForm();setSuccess(editing?'Dokumen kendaraan diperbarui.':'Dokumen kendaraan tersimpan.');await load()
 }catch(e2){setError(e2.message)}finally{setSaving(false)}}
 const remove=async d=>{if(!canManage)return;if(!window.confirm(`Hapus dokumen ${d.jenis_dokumen}${d.nomor_dokumen?` ${d.nomor_dokumen}`:''}?`))return;setSaving(true);setError('');try{const {error}=await supabase.from('dokumen_kendaraan').delete().eq('id',d.id);if(error)throw error;if(d.file_path)await supabase.storage.from('dokumen-kendaraan').remove([d.file_path]);setSuccess('Dokumen dihapus.');await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 const openFile=async path=>{try{const {data,error}=await supabase.storage.from('dokumen-kendaraan').createSignedUrl(path,3600);if(error)throw error;if(data?.signedUrl)window.open(data.signedUrl,'_blank','noopener,noreferrer')}catch(e){setError(e.message)}}
 const edit=d=>{setEditing(d);setForm({kendaraan_id:String(d.kendaraan_id),jenis_dokumen:d.jenis_dokumen||'STNK',nomor_dokumen:d.nomor_dokumen||'',tanggal_terbit:d.tanggal_terbit||'',tanggal_berlaku_mulai:d.tanggal_berlaku_mulai||'',tanggal_jatuh_tempo:d.tanggal_jatuh_tempo||'',keterangan:d.keterangan||''});setFile(null);window.scrollTo({top:0,behavior:'smooth'})}
 return <div className="x-page"><div className="x-head"><div><span className="eyebrow">DOKUMEN KENDARAAN</span><h2>Dokumen Armada</h2><p>Kelola STNK, pajak, KIR, dan dokumen kendaraan beserta masa berlaku.</p></div><button className="x-btn secondary" onClick={load} disabled={loading}>↻ Refresh</button></div>{error&&<Alert type="error">{error}</Alert>}{success&&<Alert>{success}</Alert>}
  {canManage&&<section className="x-card"><div className="x-card-title"><div><h3>{editing?'Edit Dokumen':'Tambah Dokumen'}</h3>{editing&&<p>Biarkan file kosong untuk mempertahankan file lama.</p>}</div>{editing&&<button className="x-btn secondary" type="button" onClick={resetForm}>Batal Edit</button>}</div><form className="x-grid" onSubmit={save}><label>Kendaraan<select value={form.kendaraan_id} onChange={e=>setForm({...form,kendaraan_id:e.target.value})}><option value="">Pilih kendaraan</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.nomor_polisi} — {v.merk} {v.tipe||''}</option>)}</select></label><label>Jenis Dokumen<select value={form.jenis_dokumen} onChange={e=>setForm({...form,jenis_dokumen:e.target.value})}><option>STNK</option><option>PAJAK</option><option>KIR</option><option>5_TAHUNAN</option><option>LAINNYA</option></select></label><label>Nomor Dokumen<input value={form.nomor_dokumen} onChange={e=>setForm({...form,nomor_dokumen:e.target.value})}/></label><label>Tanggal Terbit<input type="date" value={form.tanggal_terbit} onChange={e=>setForm({...form,tanggal_terbit:e.target.value})}/></label><label>Berlaku Mulai<input type="date" value={form.tanggal_berlaku_mulai} onChange={e=>setForm({...form,tanggal_berlaku_mulai:e.target.value})}/></label><label>Jatuh Tempo<input type="date" value={form.tanggal_jatuh_tempo} onChange={e=>setForm({...form,tanggal_jatuh_tempo:e.target.value})}/></label><label>File<input type="file" accept=".pdf,image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label className="full">Keterangan<textarea value={form.keterangan} onChange={e=>setForm({...form,keterangan:e.target.value})}/></label><div className="full x-actions"><button className="x-btn primary" disabled={saving}>{saving?'Menyimpan...':editing?'Perbarui Dokumen':'Simpan Dokumen'}</button></div></form></section>}
  <section className="x-card"><div className="x-card-title"><div><h3>Daftar Dokumen</h3><p>Dokumen private dibuka menggunakan signed URL.</p></div></div><div className="x-grid"><label>Pencarian<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Plat, jenis, nomor..."/></label><label>Status<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="SEMUA">Semua</option><option value="EXPIRED">Expired</option><option value="SEGERA">≤ 30 hari</option><option value="AMAN">Aman</option><option value="TANPA_TANGGAL">Tanpa tanggal</option></select></label></div><div className="x-table-wrap">{loading?<div className="x-empty">Memuat...</div>:filtered.length===0?<div className="x-empty">Belum ada dokumen yang cocok.</div>:<table className="x-table"><thead><tr><th>Kendaraan</th><th>Jenis</th><th>Nomor</th><th>Berlaku</th><th>Jatuh Tempo</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{filtered.map(d=>{const days=d.tanggal_jatuh_tempo?Math.ceil((new Date(d.tanggal_jatuh_tempo)-new Date())/86400000):null;return <tr key={d.id}><td><b>{vehicleMap[d.kendaraan_id]?.nomor_polisi||'-'}</b><small>{vehicleMap[d.kendaraan_id]?.merk||''}</small></td><td>{d.jenis_dokumen}</td><td>{d.nomor_dokumen||'-'}</td><td>{fmt(d.tanggal_berlaku_mulai)}</td><td>{fmt(d.tanggal_jatuh_tempo)}</td><td><span className="x-pill">{days===null?'Tanpa tanggal':days<0?'Expired':days<=30?`${days} hari lagi`:'Aman'}</span></td><td>{d.file_path&&<button className="x-link" onClick={()=>openFile(d.file_path)}>Lihat</button>}{canManage&&<><button className="x-link" onClick={()=>edit(d)}>Edit</button><button className="x-link" onClick={()=>remove(d)} disabled={saving}>Hapus</button></>}</td></tr>})}</tbody></table>}</div></section>
 </div>
}
