import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import './TransportOperationsFixed.css'
const EMPTY={kendaraan_id:'',jenis_dokumen:'STNK',nomor_dokumen:'',tanggal_terbit:'',tanggal_berlaku_mulai:'',tanggal_jatuh_tempo:'',keterangan:''}
const fmt=v=>v?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'}).format(new Date(v)):'-'
const Alert=({type='success',children})=><div className={`x-alert ${type}`}>{children}</div>
export default function DocumentsFeaturePage(){
 const [docs,setDocs]=useState([]),[vehicles,setVehicles]=useState([]),[form,setForm]=useState(EMPTY),[file,setFile]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const vehicleMap=useMemo(()=>Object.fromEntries(vehicles.map(v=>[v.id,v])),[vehicles])
 const load=async()=>{setLoading(true);setError('');const [d,v]=await Promise.all([supabase.from('dokumen_kendaraan').select('*').order('tanggal_jatuh_tempo',{ascending:true}),supabase.from('kendaraan').select('id,nomor_polisi,merk,tipe').order('nomor_polisi')]);if(d.error)setError(`Dokumen: ${d.error.message}`);if(v.error)setError(e=>e||`Kendaraan: ${v.error.message}`);setDocs(d.data||[]);setVehicles(v.data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const save=async e=>{e.preventDefault();if(!form.kendaraan_id||!form.tanggal_jatuh_tempo){setError('Kendaraan dan tanggal jatuh tempo wajib diisi.');return}setSaving(true);setError('');try{let path=null;if(file){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');path=`${form.kendaraan_id}/${Date.now()}-${crypto.randomUUID()}-${safe}`;const {error}=await supabase.storage.from('dokumen-kendaraan').upload(path,file,{upsert:false,contentType:file.type||undefined});if(error)throw error}const {error}=await supabase.from('dokumen_kendaraan').insert({...form,kendaraan_id:Number(form.kendaraan_id),file_path:path});if(error)throw error;setForm(EMPTY);setFile(null);setSuccess('Dokumen kendaraan tersimpan.');await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 const openFile=async path=>{try{const {data,error}=await supabase.storage.from('dokumen-kendaraan').createSignedUrl(path,3600);if(error)throw error;if(data?.signedUrl)window.open(data.signedUrl,'_blank','noopener,noreferrer')}catch(e){setError(e.message)}}
 return <div className="x-page"><div className="x-head"><div><span className="eyebrow">DOKUMEN KENDARAAN</span><h2>Dokumen Armada</h2><p>Kelola STNK, pajak, KIR, dan dokumen kendaraan beserta masa berlaku.</p></div><button className="x-btn secondary" onClick={load}>↻ Refresh</button></div>{error&&<Alert type="error">{error}</Alert>}{success&&<Alert>{success}</Alert>}<section className="x-card"><div className="x-card-title"><h3>Tambah Dokumen</h3></div><form className="x-grid" onSubmit={save}><label>Kendaraan<select value={form.kendaraan_id} onChange={e=>setForm({...form,kendaraan_id:e.target.value})}><option value="">Pilih kendaraan</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.nomor_polisi} — {v.merk} {v.tipe||''}</option>)}</select></label><label>Jenis Dokumen<select value={form.jenis_dokumen} onChange={e=>setForm({...form,jenis_dokumen:e.target.value})}><option>STNK</option><option>PAJAK</option><option>KIR</option><option>5_TAHUNAN</option><option>LAINNYA</option></select></label><label>Nomor Dokumen<input value={form.nomor_dokumen} onChange={e=>setForm({...form,nomor_dokumen:e.target.value})}/></label><label>Tanggal Terbit<input type="date" value={form.tanggal_terbit} onChange={e=>setForm({...form,tanggal_terbit:e.target.value})}/></label><label>Berlaku Mulai<input type="date" value={form.tanggal_berlaku_mulai} onChange={e=>setForm({...form,tanggal_berlaku_mulai:e.target.value})}/></label><label>Jatuh Tempo<input type="date" value={form.tanggal_jatuh_tempo} onChange={e=>setForm({...form,tanggal_jatuh_tempo:e.target.value})}/></label><label>File<input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label className="full">Keterangan<textarea value={form.keterangan} onChange={e=>setForm({...form,keterangan:e.target.value})}/></label><div className="full x-actions"><button className="x-btn primary" disabled={saving}>{saving?'Menyimpan...':'Simpan Dokumen'}</button></div></form></section><section className="x-card"><div className="x-table-wrap">{loading?<div className="x-empty">Memuat...</div>:docs.length===0?<div className="x-empty">Belum ada dokumen kendaraan.</div>:<table className="x-table"><thead><tr><th>Kendaraan</th><th>Jenis</th><th>Nomor</th><th>Berlaku</th><th>Jatuh Tempo</th><th>Status</th><th>File</th></tr></thead><tbody>{docs.map(d=>{const days=Math.ceil((new Date(d.tanggal_jatuh_tempo)-new Date())/86400000);return <tr key={d.id}><td><b>{vehicleMap[d.kendaraan_id]?.nomor_polisi||'-'}</b><small>{vehicleMap[d.kendaraan_id]?.merk||''}</small></td><td>{d.jenis_dokumen}</td><td>{d.nomor_dokumen||'-'}</td><td>{fmt(d.tanggal_berlaku_mulai)}</td><td>{fmt(d.tanggal_jatuh_tempo)}</td><td><span className="x-pill">{days<0?'Expired':days<=30?`${days} hari lagi`:'Aman'}</span></td><td>{d.file_path?<button className="x-link" onClick={()=>openFile(d.file_path)}>Lihat</button>:'-'}</td></tr>})}</tbody></table>}</div></section></div>
}
