import { useEffect, useMemo, useRef, useState } from 'react'
import { supabase } from '../lib/supabase'
import './TransportOperationsFixed.css'
import { formatDateSafe } from '../utils/dateSafe'
import { decodeExcelMeta } from '../utils/excelSourceMeta.js'

const EMPTY={kendaraan_id:'',jenis_dokumen:'STNK',nomor_dokumen:'',tanggal_terbit:'',tanggal_berlaku_mulai:'',tanggal_jatuh_tempo:'',keterangan:''}
const fmt=v=>formatDateSafe(v)
const Alert=({type='success',children})=><div className={`x-alert ${type}`}>{children}</div>
const isInteractiveTarget=target=>Boolean(target?.closest?.('button,input,select,textarea,a'))

export default function DocumentsFeaturePage({profile}){
 const [docs,setDocs]=useState([]),[vehicles,setVehicles]=useState([]),[form,setForm]=useState(EMPTY),[file,setFile]=useState(null)
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const [viewMode,setViewMode]=useState('excel')
 const [editing,setEditing]=useState(null),[query]=useState(''),[statusFilter]=useState('SEMUA'),[selectedDocIds,setSelectedDocIds]=useState([]),[selectionMode,setSelectionMode]=useState(false)
 const canManage=['ADMIN','TRANSPORT'].includes(profile?.role)
 const vehicleMap=useMemo(()=>Object.fromEntries(vehicles.map(v=>[v.id,v])),[vehicles])
 const pressRef=useRef(null),ignoreClickRef=useRef(false)
 const clearPress=()=>{if(pressRef.current?.timer)window.clearTimeout(pressRef.current.timer);pressRef.current=null}
 const load=async()=>{setLoading(true);setError('');const [d,v]=await Promise.all([supabase.from('dokumen_kendaraan').select('*').order('tanggal_jatuh_tempo',{ascending:true}),supabase.from('kendaraan').select('id,nomor_polisi,merk,tipe,tahun,nomor_rangka,pemilik,foto_stnk_path').order('nomor_polisi')]);if(d.error)setError(`Dokumen: ${d.error.message}`);if(v.error)setError(e=>e||`Kendaraan: ${v.error.message}`);setDocs(d.data||[]);setVehicles(v.data||[]);setSelectedDocIds([]);setSelectionMode(false);setLoading(false)}
 useEffect(()=>{load();const handleImported=(event)=>{if(['dokumen','kendaraan'].includes(event.detail?.context))load()};window.addEventListener('transport:data-imported',handleImported);return()=>window.removeEventListener('transport:data-imported',handleImported)},[])
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return docs.filter(d=>{const days=d.tanggal_jatuh_tempo?Math.ceil((new Date(d.tanggal_jatuh_tempo)-new Date())/86400000):null;const status=days===null?'TANPA_TANGGAL':days<0?'EXPIRED':days<=30?'SEGERA':'AMAN';const text=[d.jenis_dokumen,d.nomor_dokumen,d.keterangan,vehicleMap[d.kendaraan_id]?.nomor_polisi,vehicleMap[d.kendaraan_id]?.merk].filter(Boolean).join(' ').toLowerCase();return (!q||text.includes(q))&&(statusFilter==='SEMUA'||status===statusFilter)})},[docs,vehicleMap,query,statusFilter])
 const monitorRows=useMemo(()=>vehicles.map((v,index)=>{const byType={};docs.filter(d=>d.kendaraan_id===v.id).forEach(d=>{byType[d.jenis_dokumen]=d});const sourceDoc=Object.values(byType).find(d=>decodeExcelMeta(d.keterangan).meta?.source==='STNK_DAN_KIR');const meta=sourceDoc?decodeExcelMeta(sourceDoc.keterangan).meta:null;return{no:Number(meta?.source_no)||index+1,merk:meta?.merk||v.merk||'-',tipe:meta?.type||v.tipe||'-',nomor_polisi:meta?.nomor_polisi||v.nomor_polisi||'-',tahun:meta?.tahun||v.tahun||'-',nomor_rangka:meta?.nomor_rangka||'-',stnk:byType.STNK?.tanggal_jatuh_tempo||'-',kir:byType.KIR?.tanggal_jatuh_tempo||'-',lima_tahun:byType['5_TAHUNAN']?.tanggal_jatuh_tempo||'-',pemilik:meta?.pemilik||v.pemilik||'-'}}),[vehicles,docs])
 const resetForm=()=>{setForm(EMPTY);setFile(null);setEditing(null)}
 const save=async e=>{e.preventDefault();if(!canManage)return;if(!form.kendaraan_id||!form.tanggal_jatuh_tempo){setError('Kendaraan dan tanggal jatuh tempo wajib diisi.');return}setSaving(true);setError('');setSuccess('');let newPath=null;try{let path=editing?.file_path||null;if(file){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');path=`${form.kendaraan_id}/${Date.now()}-${crypto.randomUUID()}-${safe}`;newPath=path;const {error}=await supabase.storage.from('dokumen-kendaraan').upload(path,file,{upsert:false,contentType:file.type||undefined});if(error)throw error}
  const payload={...form,kendaraan_id:Number(form.kendaraan_id),file_path:path}
  const result=editing?await supabase.from('dokumen_kendaraan').update(payload).eq('id',editing.id).select('*').single():await supabase.from('dokumen_kendaraan').insert(payload).select('*').single()
  if(result.error)throw result.error
  if(editing&&file&&editing.file_path)await supabase.storage.from('dokumen-kendaraan').remove([editing.file_path])
  const savedDoc=result.data
  setDocs(current=>{const next=editing?current.map(row=>row.id===savedDoc.id?savedDoc:row):[savedDoc,...current];return next.sort((a,b)=>String(a.tanggal_jatuh_tempo||'').localeCompare(String(b.tanggal_jatuh_tempo||'')))});resetForm();setSuccess(editing?'Dokumen kendaraan diperbarui.':'Dokumen kendaraan tersimpan.')
 }catch(e2){if(newPath)await supabase.storage.from('dokumen-kendaraan').remove([newPath]);setError(e2.message)}finally{setSaving(false)}}
 const remove=async d=>{if(!canManage)return;if(!window.confirm(`Hapus dokumen ${d.jenis_dokumen}${d.nomor_dokumen?` ${d.nomor_dokumen}`:''}?`))return;setSaving(true);setError('');try{const {error}=await supabase.from('dokumen_kendaraan').delete().eq('id',d.id);if(error)throw error;if(d.file_path){const storageResult=await supabase.storage.from('dokumen-kendaraan').remove([d.file_path]);if(storageResult.error)setError(`Data dokumen terhapus, tetapi file storage gagal dibersihkan: ${storageResult.error.message}`)}setDocs(current=>current.filter(row=>row.id!==d.id));setSelectedDocIds(current=>current.filter(id=>id!==d.id));setSuccess('Dokumen dihapus.')}catch(e){setError(e.message)}finally{setSaving(false)}}
 const deleteSelected=async()=>{if(!canManage||!selectedDocIds.length)return;if(!window.confirm(`Hapus ${selectedDocIds.length} dokumen yang dipilih?`))return;setSaving(true);setError('');setSuccess('');try{const selectedDocs=docs.filter(d=>selectedDocIds.includes(d.id));const result=await supabase.from('dokumen_kendaraan').delete().in('id',selectedDocIds);if(result.error)throw result.error;const paths=selectedDocs.map(d=>d.file_path).filter(Boolean);if(paths.length){const storageResult=await supabase.storage.from('dokumen-kendaraan').remove(paths);if(storageResult.error)setError(`Data terhapus, tetapi sebagian file storage gagal dibersihkan: ${storageResult.error.message}`)}setDocs(current=>current.filter(row=>!selectedDocIds.includes(row.id)));setSelectedDocIds([]);setSelectionMode(false);setSuccess(`${selectedDocs.length} dokumen berhasil dihapus.`)}catch(e){setError(e.message)}finally{setSaving(false)}}
 const openFile=async path=>{try{const {data,error}=await supabase.storage.from('dokumen-kendaraan').createSignedUrl(path,3600);if(error)throw error;if(data?.signedUrl)window.open(data.signedUrl,'_blank','noopener,noreferrer')}catch(e){setError(e.message)}}
 const openStnkPhoto=async path=>{try{if(!path)throw new Error('Foto STNK belum tersedia untuk kendaraan ini.');const {data,error}=await supabase.storage.from('kendaraan').createSignedUrl(path,3600);if(error)throw error;if(!data?.signedUrl)throw new Error('Foto STNK tidak dapat dibuka.');window.open(data.signedUrl,'_blank','noopener,noreferrer')}catch(e){setError(e.message)}}
 const edit=d=>{setEditing(d);setForm({kendaraan_id:String(d.kendaraan_id),jenis_dokumen:d.jenis_dokumen||'STNK',nomor_dokumen:d.nomor_dokumen||'',tanggal_terbit:d.tanggal_terbit||'',tanggal_berlaku_mulai:d.tanggal_berlaku_mulai||'',tanggal_jatuh_tempo:d.tanggal_jatuh_tempo||'',keterangan:d.keterangan||''});setFile(null);window.scrollTo({top:0,behavior:'smooth'})}
 const armLongPress=(event,id)=>{if(!canManage||(event.button!==undefined&&event.button!==0)||isInteractiveTarget(event.target)||selectionMode)return;clearPress();pressRef.current={x:event.clientX,y:event.clientY,timer:window.setTimeout(()=>{setSelectionMode(true);setSelectedDocIds(current=>current.includes(id)?current:[...current,id]);ignoreClickRef.current=true;pressRef.current=null},480)};event.currentTarget.setPointerCapture?.(event.pointerId)}
 const moveLongPress=event=>{const state=pressRef.current;if(state&&Math.hypot(event.clientX-state.x,event.clientY-state.y)>10)clearPress()}
 const finishLongPress=()=>clearPress()
 const toggleDoc=id=>setSelectedDocIds(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id])
 const allSelected=filtered.length>0&&filtered.every(d=>selectedDocIds.includes(d.id))
 const toggleAll=()=>setSelectedDocIds(current=>allSelected?current.filter(id=>!filtered.some(d=>d.id===id)):Array.from(new Set([...current,...filtered.map(d=>d.id)])))
 const exitSelection=()=>{setSelectedDocIds([]);setSelectionMode(false)}
 return <div className="x-page"><div className="x-head"><div><span className="eyebrow">DOKUMEN KENDARAAN</span><h2>Dokumen Armada</h2><p>Kelola STNK, pajak, KIR, dan dokumen kendaraan beserta masa berlaku.</p></div><button className="x-btn secondary" onClick={load} disabled={loading}>↻ Refresh</button></div>{error&&<Alert type="error">{error}</Alert>}{success&&<Alert>{success}</Alert>}
  <div className="x-tabs"><button className={viewMode==='excel'?'active':''} onClick={()=>setViewMode('excel')}>Monitoring Excel</button>{canManage&&<button className={viewMode==='detail'?'active':''} onClick={()=>setViewMode('detail')}>Detail Dokumen</button>}</div>{viewMode==='detail'&&canManage&&<section className="x-card"><div className="x-card-title"><div><h3>{editing?'Edit Dokumen':'Tambah Dokumen'}</h3>{editing&&<p>Biarkan file kosong untuk mempertahankan file lama.</p>}</div>{editing&&<button className="x-btn secondary" type="button" onClick={resetForm}>Batal Edit</button>}</div><form className="x-grid" onSubmit={save}><label>Kendaraan<select value={form.kendaraan_id} onChange={e=>setForm({...form,kendaraan_id:e.target.value})}><option value="">Pilih kendaraan</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.nomor_polisi} — {v.merk} {v.tipe||''}</option>)}</select></label><label>Jenis Dokumen<select value={form.jenis_dokumen} onChange={e=>setForm({...form,jenis_dokumen:e.target.value})}><option>STNK</option><option>PAJAK</option><option>KIR</option><option>5_TAHUNAN</option><option>LAINNYA</option></select></label><label>Nomor Dokumen<input value={form.nomor_dokumen} onChange={e=>setForm({...form,nomor_dokumen:e.target.value})}/></label><label>Tanggal Terbit<input type="date" value={form.tanggal_terbit} onChange={e=>setForm({...form,tanggal_terbit:e.target.value})}/></label><label>Berlaku Mulai<input type="date" value={form.tanggal_berlaku_mulai} onChange={e=>setForm({...form,tanggal_berlaku_mulai:e.target.value})}/></label><label>Jatuh Tempo<input type="date" value={form.tanggal_jatuh_tempo} onChange={e=>setForm({...form,tanggal_jatuh_tempo:e.target.value})}/></label><label>File<input type="file" accept=".pdf,image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label className="full">Keterangan<textarea value={form.keterangan} onChange={e=>setForm({...form,keterangan:e.target.value})}/></label><div className="full x-actions"><button className="x-btn primary" disabled={saving}>{saving?'Menyimpan...':editing?'Perbarui Dokumen':'Simpan Dokumen'}</button></div></form></section>}
  {viewMode==='excel'&&<section className="x-card"><div className="x-card-title"><div><h3>Monitoring STNK DAN KIR</h3><p>Kolom mengikuti Excel: NO, MERK, TYPE, NO.POLISI, TAHUN, No Ranka, STNK, KIR, 5 TAHUN, PEMILIK.</p></div></div><div className="x-table-wrap"><table className="x-table"><thead><tr><th>NO</th><th>MERK</th><th>TYPE</th><th>NO.POLISI</th><th>TAHUN</th><th>No Ranka</th><th>STNK</th><th>Foto STNK</th><th>KIR</th><th>5 TAHUN</th><th>PEMILIK</th></tr></thead><tbody>{monitorRows.map(row=><tr key={`${row.no}-${row.nomor_polisi}`}><td>{row.no}</td><td>{row.merk}</td><td>{row.tipe}</td><td>{row.nomor_polisi}</td><td>{row.tahun}</td><td>{row.nomor_rangka}</td><td>{fmt(row.stnk)}</td><td>{row.foto_stnk_path?<button className="x-link" type="button" onClick={()=>openStnkPhoto(row.foto_stnk_path)}>Lihat</button>:<span>-</span>}</td><td>{fmt(row.kir)}</td><td>{fmt(row.lima_tahun)}</td><td>{row.pemilik}</td></tr>)}</tbody></table></div></section>}
  <section className="x-card"><div className="x-card-title"><div><h3>Daftar Dokumen</h3><p>Dokumen private dibuka menggunakan signed URL.</p></div></div>{selectionMode&&<div className="x-selection-bar"><div className="x-selection-meta"><span>Mode pilih dokumen</span><strong>{selectedDocIds.length} dipilih</strong></div><div className="x-selection-actions"><button className="ghost" onClick={toggleAll}>{allSelected?'Batalkan semua':'Pilih semua'}</button><button className="ghost" onClick={exitSelection}>Batal</button><button className="danger" onClick={deleteSelected} disabled={saving||!selectedDocIds.length}>Hapus {selectedDocIds.length} Dokumen</button></div></div>}{!selectionMode&&filtered.length>0&&<p className="x-selection-hint">Tekan dan tahan satu baris sekitar setengah detik untuk memilih banyak dokumen.</p>}<div className={`x-table-wrap ${selectionMode?'x-selection-active':''}`}>{loading?<div className="x-empty">Memuat...</div>:filtered.length===0?<div className="x-empty">Belum ada dokumen yang cocok.</div>:<table data-no-bulk-select="true" className={`x-table ${selectionMode?'x-selection-active':''}`}><thead><tr>{selectionMode&&<th className="x-select-cell"><input type="checkbox" aria-label="Pilih semua dokumen" checked={allSelected} onChange={toggleAll}/></th>}<th>Kendaraan</th><th>Jenis</th><th>Nomor</th><th>Berlaku</th><th>Jatuh Tempo</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{filtered.map(d=>{const days=d.tanggal_jatuh_tempo?Math.ceil((new Date(d.tanggal_jatuh_tempo)-new Date())/86400000):null;const selected=selectedDocIds.includes(d.id);return <tr key={d.id} className={`x-longpress-row ${selected?'x-selected':''}`} onPointerDown={e=>armLongPress(e,d.id)} onPointerMove={moveLongPress} onPointerUp={finishLongPress} onPointerCancel={finishLongPress} onClick={e=>{if(isInteractiveTarget(e.target))return;if(ignoreClickRef.current){ignoreClickRef.current=false;return}if(selectionMode)toggleDoc(d.id)}}>{selectionMode&&<td className="x-select-cell"><input type="checkbox" aria-label={`Pilih dokumen ${d.id}`} checked={selected} onChange={()=>toggleDoc(d.id)}/></td>}<td><b>{vehicleMap[d.kendaraan_id]?.nomor_polisi||'-'}</b><small>{vehicleMap[d.kendaraan_id]?.merk||''}</small></td><td>{d.jenis_dokumen}</td><td>{d.nomor_dokumen||'-'}</td><td>{fmt(d.tanggal_berlaku_mulai)}</td><td>{fmt(d.tanggal_jatuh_tempo)}</td><td><span className="x-pill">{days===null?'Tanpa tanggal':days<0?'Expired':days<=30?`${days} hari lagi`:'Aman'}</span></td><td>{d.file_path&&<button className="x-link" onClick={()=>openFile(d.file_path)}>Lihat</button>}{canManage&&<><button className="x-link" onClick={()=>edit(d)}>Edit</button><button className="x-link" onClick={()=>remove(d)} disabled={saving}>Hapus</button></>}</td></tr>})}</tbody></table>}</div></section>
 </div>
}