import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import './TransportOperationsFixed.css'
const money=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v||0))
const date=v=>v?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'}).format(new Date(v)):'-'
export default function ReportsFeaturePage(){
 const [v,setV]=useState([]),[s,setS]=useState([]),[r,setR]=useState([]),[c,setC]=useState([]),[p,setP]=useState([]),[d,setD]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{(async()=>{const rs=await Promise.all([supabase.from('kendaraan').select('*'),supabase.from('service').select('*'),supabase.from('permintaan_service').select('*'),supabase.from('kontrak_sewa').select('*'),supabase.from('pembayaran_sewa').select('*'),supabase.from('dokumen_kendaraan').select('*')]);for(const [i,x] of rs.entries())if(x.error)setError(e=>e||`Gagal memuat laporan bagian ${i+1}: ${x.error.message}`);setV(rs[0].data||[]);setS(rs[1].data||[]);setR(rs[2].data||[]);setC(rs[3].data||[]);setP(rs[4].data||[]);setD(rs[5].data||[]);setLoading(false)})()},[])
 const serviceCost=s.reduce((n,x)=>n+Number(x.biaya_aktual??x.estimasi_biaya??0),0),rentalCost=p.reduce((n,x)=>n+Number(x.jumlah_dibayar??0),0),expired=d.filter(x=>x.tanggal_jatuh_tempo&&new Date(x.tanggal_jatuh_tempo)<new Date()).length,soon=d.filter(x=>x.tanggal_jatuh_tempo&&new Date(x.tanggal_jatuh_tempo)>=new Date()&&new Date(x.tanggal_jatuh_tempo)<=new Date(Date.now()+30*86400000)).length
 if(loading)return <div className="x-page"><div className="x-card"><div className="x-empty">Memuat laporan...</div></div></div>
 return <div className="x-page"><div className="x-head"><div><span className="eyebrow">LAPORAN & REKAP</span><h2>Laporan Transport</h2><p>Ringkasan armada, service, biaya, sewa, pembayaran, dan dokumen.</p></div></div>{error&&<div className="x-alert error">{error}</div>}<div className="x-stat-grid">{[['Kendaraan',v.length],['Pengajuan',r.length],['Service',s.length],['Kontrak Sewa',c.length],['Biaya Service',money(serviceCost)],['Pembayaran Sewa',money(rentalCost)],['Dokumen Expired',expired],['Dokumen ≤30 Hari',soon]].map(([l,n])=><div className="x-stat" key={l}><span>{l}</span><b>{n}</b></div>)}</div><section className="x-card"><div className="x-card-title"><h3>Status Armada</h3></div><div className="x-stat-grid">{['ACTIVE','SERVICE','TIDAK_AKTIF'].map(x=><div className="x-stat" key={x}><span>{x==='ACTIVE'?'Aktif':x==='SERVICE'?'Service':'Tidak Aktif'}</span><b>{v.filter(k=>k.status===x).length}</b></div>)}</div></section><section className="x-card"><div className="x-card-title"><h3>Service Selesai Terbaru</h3></div><div className="x-table-wrap"><table className="x-table"><thead><tr><th>Tanggal</th><th>Kendaraan</th><th>Jenis</th><th>Biaya</th><th>Status</th></tr></thead><tbody>{s.filter(x=>x.status==='SELESAI').slice(0,20).map(x=><tr key={x.id}><td>{date(x.tanggal_service)}</td><td>{v.find(k=>k.id===x.kendaraan_id)?.nomor_polisi||'-'}</td><td>{x.jenis_service||'-'}</td><td>{money(x.biaya_aktual??x.estimasi_biaya)}</td><td>{x.status}</td></tr>)}{!s.some(x=>x.status==='SELESAI')&&<tr><td colSpan="5">Belum ada service selesai.</td></tr>}</tbody></table></div></section><section className="x-card"><div className="x-card-title"><h3>Pembayaran Sewa Terlambat / Belum Lunas</h3></div><div className="x-table-wrap"><table className="x-table"><thead><tr><th>Kontrak</th><th>Jatuh Tempo</th><th>Tagihan</th><th>Dibayar</th><th>Status</th></tr></thead><tbody>{p.filter(x=>x.status==='TERLAMBAT'||(x.status==='BELUM_LUNAS'&&x.tanggal_jatuh_tempo&&new Date(x.tanggal_jatuh_tempo)<new Date())).slice(0,20).map(x=><tr key={x.id}><td>#{x.kontrak_sewa_id}</td><td>{date(x.tanggal_jatuh_tempo)}</td><td>{money(x.jumlah_tagihan)}</td><td>{money(x.jumlah_dibayar)}</td><td>{x.status}</td></tr>)}{!p.some(x=>x.status==='TERLAMBAT'||(x.status==='BELUM_LUNAS'&&x.tanggal_jatuh_tempo&&new Date(x.tanggal_jatuh_tempo)<new Date()))&&<tr><td colSpan="5">Tidak ada pembayaran bermasalah.</td></tr>}</tbody></table></div></section></div>
}
