import { useEffect, useMemo, useState } from 'react'
import { supabase } from './lib/supabase'
import KendaraanPage from './modules/KendaraanPage'
import PermintaanServicePage from './modules/PermintaanServicePage'
import { ServicePage, RentalPage, DocumentsPage, ReportsPage, UsersPage } from './modules/TransportOperationsPage'
import './App.css'

const REMEMBERED_EMAIL_KEY = 'transport_remembered_email'

const ROLE_LABELS = { ADMIN: 'Administrator', TRANSPORT: 'Transport', OPERASIONAL: 'Operasional', ATASAN_TRANSPORT: 'Atasan Transport', DIREKTUR: 'Direktur', AKUNTANSI: 'Akuntansi' }
const ROLE_ACCESS = {
  ADMIN: ['dashboard', 'kendaraan', 'pengajuan', 'service', 'sewa', 'dokumen', 'laporan', 'pengguna'],
  TRANSPORT: ['dashboard', 'kendaraan', 'pengajuan', 'service', 'sewa', 'dokumen', 'laporan'],
  OPERASIONAL: ['dashboard', 'pengajuan'],
  ATASAN_TRANSPORT: ['dashboard', 'pengajuan', 'service', 'laporan'],
  DIREKTUR: ['dashboard', 'service', 'laporan'],
  AKUNTANSI: ['dashboard', 'sewa', 'laporan'],
}
const NAV_ITEMS = [
  { id: 'dashboard', label: 'Dashboard', icon: '⌂' },
  { id: 'kendaraan', label: 'Kendaraan', icon: '▣' },
  { id: 'pengajuan', label: 'Pengajuan Service', icon: '↗' },
  { id: 'service', label: 'Service & Perbaikan', icon: '⚙' },
  { id: 'sewa', label: 'Kendaraan Sewa', icon: '▤' },
  { id: 'dokumen', label: 'Dokumen', icon: '□' },
  { id: 'laporan', label: 'Laporan', icon: '▥' },
  { id: 'pengguna', label: 'Pengguna', icon: '♙' },
]
const STATS = [['vehicles', 'Total Kendaraan', 'Data kendaraan terdaftar', '▣'], ['activeVehicles', 'Kendaraan Aktif', 'Siap digunakan', '✓'], ['inService', 'Sedang Service', 'Perlu dipantau', '⚙'], ['pendingRequests', 'Pengajuan Menunggu', 'Perlu diproses', '↗']]

function AppTransport() {
  const [session, setSession] = useState(null), [profile, setProfile] = useState(null), [loading, setLoading] = useState(true), [activePage, setActivePage] = useState('dashboard'), [sidebarOpen, setSidebarOpen] = useState(false)
  const [stats, setStats] = useState({ vehicles: 0, activeVehicles: 0, inService: 0, pendingRequests: 0 }), [statsLoading, setStatsLoading] = useState(false), [errorMessage, setErrorMessage] = useState('')
  const [email, setEmail] = useState(() => localStorage.getItem(REMEMBERED_EMAIL_KEY) || ''), [password, setPassword] = useState(''), [showPassword, setShowPassword] = useState(false), [rememberMe, setRememberMe] = useState(true), [submitting, setSubmitting] = useState(false)
  const allowedPages = useMemo(() => ROLE_ACCESS[profile?.role] || ['dashboard'], [profile?.role])
  const visibleNavItems = useMemo(() => NAV_ITEMS.filter((item) => allowedPages.includes(item.id)), [allowedPages])

  const loadProfile = async (userId) => { const { data, error } = await supabase.from('profiles').select('id,nama_lengkap,email,nomor_hp,role,aktif').eq('id', userId).single(); if (error || !data) { console.error('Profile error:', error); setProfile(null); setErrorMessage('Profil pengguna tidak dapat dimuat.'); return } if (!data.aktif) { await supabase.auth.signOut(); setSession(null); setProfile(null); setErrorMessage('Akun ini sedang dinonaktifkan. Hubungi administrator.'); return } setProfile(data); setErrorMessage('') }
  useEffect(() => { let mounted = true; const initialize = async () => { const { data, error } = await supabase.auth.getSession(); if (!mounted) return; if (error) setErrorMessage('Sesi login tidak dapat diperiksa. Silakan coba lagi.'); setSession(data.session); if (data.session?.user) await loadProfile(data.session.user.id); setLoading(false) }; initialize(); const { data: { subscription } } = supabase.auth.onAuthStateChange(async (_event, nextSession) => { if (!mounted) return; setSession(nextSession); if (nextSession?.user) await loadProfile(nextSession.user.id); else setProfile(null) }); return () => { mounted = false; subscription.unsubscribe() } }, [])
  useEffect(() => { if (session && profile && !allowedPages.includes(activePage)) setActivePage('dashboard') }, [activePage, allowedPages, profile, session])
  useEffect(() => { if (!session || !profile || activePage !== 'dashboard') return; let cancelled = false; const loadStats = async () => { setStatsLoading(true); const [vehicles, activeVehicles, inService, pendingRequests] = await Promise.all([supabase.from('kendaraan').select('id', { count: 'exact', head: true }), supabase.from('kendaraan').select('id', { count: 'exact', head: true }).eq('status', 'ACTIVE'), supabase.from('kendaraan').select('id', { count: 'exact', head: true }).eq('status', 'SERVICE'), supabase.from('permintaan_service').select('id', { count: 'exact', head: true }).in('status', ['MENUNGGU_TRANSPORT', 'DITERIMA_TRANSPORT', 'MENUNGGU_APPROVAL'])]); if (!cancelled) { setStats({ vehicles: vehicles.count || 0, activeVehicles: activeVehicles.count || 0, inService: inService.count || 0, pendingRequests: pendingRequests.count || 0 }); setStatsLoading(false) } }; loadStats(); return () => { cancelled = true } }, [activePage, profile, session])
  const handleLogin = async (event) => { event.preventDefault(); setErrorMessage(''); const cleanEmail = email.trim().toLowerCase(); if (!cleanEmail || !password) { setErrorMessage('Email dan password wajib diisi.'); return } setSubmitting(true); const { data, error } = await supabase.auth.signInWithPassword({ email: cleanEmail, password }); if (error || !data.user) { setErrorMessage('Email atau password tidak sesuai.'); setSubmitting(false); return } if (rememberMe) localStorage.setItem(REMEMBERED_EMAIL_KEY, cleanEmail); else localStorage.removeItem(REMEMBERED_EMAIL_KEY); setPassword(''); await loadProfile(data.user.id); setSubmitting(false) }
  const handleLogout = async () => { setSubmitting(true); await supabase.auth.signOut(); setSession(null); setProfile(null); setActivePage('dashboard'); setSubmitting(false) }

  if (loading) return <main className="auth-shell"><div className="loading-card"><div className="loading-spinner"/><p>Memuat Sistem Transport...</p></div></main>
  if (!session || !profile) return <main className="auth-shell"><section className="login-card"><div className="brand-mark">ZT</div><span className="eyebrow">PT ZAMAN TEKNINDO</span><h1>Masuk ke Sistem Transport</h1><p className="subtitle">Kelola kendaraan, service, sewa, dan operasional transport secara terpusat.</p><form onSubmit={handleLogin} noValidate><label htmlFor="email">Email</label><input id="email" type="email" autoComplete="username" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="nama@zamanteknindo.co.id" disabled={submitting}/><label htmlFor="password">Password</label><div className="password-wrap"><input id="password" type={showPassword ? 'text' : 'password'} autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Masukkan password" disabled={submitting}/><button type="button" className="password-toggle" onClick={() => setShowPassword((v) => !v)} disabled={submitting}>{showPassword ? 'Sembunyikan' : 'Lihat'}</button></div><label className="remember-option"><input type="checkbox" checked={rememberMe} onChange={(e) => setRememberMe(e.target.checked)} disabled={submitting}/><span>Ingat email di perangkat ini</span></label>{errorMessage && <div className="error-message" role="alert">{errorMessage}</div>}<button className="primary-button" type="submit" disabled={submitting}>{submitting ? 'Memproses login...' : 'Masuk'}</button></form><p className="security-note">Password tidak disimpan di perangkat. Sesi login dikelola oleh Supabase Auth.</p></section></main>

  const pageContent = { dashboard: <DashboardHome profile={profile} stats={stats} statsLoading={statsLoading} onNavigate={setActivePage}/>, kendaraan: <KendaraanPage />, pengajuan: <PermintaanServicePage profile={profile}/>, service: <ServicePage profile={profile}/>, sewa: <RentalPage profile={profile}/>, dokumen: <DocumentsPage profile={profile}/>, laporan: <ReportsPage />, pengguna: <UsersPage /> }
  return <div className="dashboard-layout">{sidebarOpen && <button className="sidebar-overlay" onClick={() => setSidebarOpen(false)} aria-label="Tutup menu"/>}<aside className={`sidebar ${sidebarOpen ? 'sidebar-open' : ''}`}><div className="sidebar-brand"><div className="brand-mark small">ZT</div><div><strong>Zaman Teknindo</strong><span>Transport System</span></div></div><div className="nav-section-label">MENU UTAMA</div><nav className="sidebar-nav" aria-label="Navigasi utama">{visibleNavItems.map((item) => <button key={item.id} className={`nav-item ${activePage === item.id ? 'active' : ''}`} onClick={() => { setActivePage(item.id); setSidebarOpen(false) }}><span className="nav-icon">{item.icon}</span><span>{item.label}</span></button>)}</nav><div className="sidebar-bottom"><div className="user-mini"><div className="avatar">{(profile.nama_lengkap || profile.email || 'U').charAt(0).toUpperCase()}</div><div className="user-mini-text"><strong>{profile.nama_lengkap || 'Pengguna'}</strong><span>{ROLE_LABELS[profile.role] || profile.role}</span></div></div><button className="logout-button" onClick={handleLogout} disabled={submitting}>Keluar</button></div></aside><main className="main-content"><header className="topbar"><button className="menu-button" onClick={() => setSidebarOpen(true)} aria-label="Buka menu">☰</button><div><span className="topbar-label">SISTEM TRANSPORT</span><h1>{NAV_ITEMS.find((item) => item.id === activePage)?.label || 'Dashboard'}</h1></div><div className="topbar-user"><div className="avatar">{(profile.nama_lengkap || profile.email || 'U').charAt(0).toUpperCase()}</div><div><strong>{profile.nama_lengkap || profile.email}</strong><span>{ROLE_LABELS[profile.role] || profile.role}</span></div></div></header><div className="content-container">{pageContent[activePage] || pageContent.dashboard}</div></main></div>
}

function DashboardHome({ profile, stats, statsLoading, onNavigate }) { const today = new Intl.DateTimeFormat('id-ID', { dateStyle: 'full' }).format(new Date()); return <><section className="page-intro"><div><span className="eyebrow">{today}</span><h2>Selamat datang, {profile.nama_lengkap || 'Pengguna'}</h2><p>Pantau kondisi kendaraan dan aktivitas transport dari satu tempat.</p></div></section><section className="stats-grid">{STATS.map(([key,label,helper,icon]) => <article className="stat-card" key={key}><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{statsLoading ? '...' : stats[key]}</strong><small>{helper}</small></div></article>)}</section><section className="dashboard-grid"><article className="panel quick-panel"><div className="panel-heading"><div><span className="eyebrow">AKSES CEPAT</span><h3>Menu yang sering digunakan</h3></div></div><div className="quick-grid"><button className="quick-action" onClick={() => onNavigate('pengajuan')}><span>↗</span><strong>Ajukan Service</strong><small>Buat permintaan untuk kendaraan</small></button><button className="quick-action" onClick={() => onNavigate('kendaraan')}><span>▣</span><strong>Data Kendaraan</strong><small>Lihat armada dan kilometer</small></button><button className="quick-action" onClick={() => onNavigate('service')}><span>⚙</span><strong>Proses Service</strong><small>Pantau pekerjaan dan biaya</small></button><button className="quick-action" onClick={() => onNavigate('dokumen')}><span>□</span><strong>Dokumen</strong><small>Kelola STNK, KIR, dan lainnya</small></button></div></article><article className="panel flow-panel"><div className="panel-heading"><div><span className="eyebrow">ALUR UTAMA</span><h3>Proses transport</h3></div></div><div className="flow-list">{['Operasional','Permintaan Service','Transport','Approval','Service','Bukti','Selesai'].map((item,i)=><div className="flow-item" key={item}><span>{i+1}</span><strong>{item}</strong></div>)}</div></article></section></> }

export default AppTransport
