create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_id uuid null,
  actor_role public.user_role null,
  action text not null check (action in ('INSERT','UPDATE','DELETE')),
  table_name text not null,
  record_id text null,
  changed_fields text[] null,
  old_data jsonb null,
  new_data jsonb null
);

create index if not exists idx_audit_log_occurred_at
  on public.audit_log (occurred_at desc);

create index if not exists idx_audit_log_table_record
  on public.audit_log (table_name, record_id, occurred_at desc);

create index if not exists idx_audit_log_actor
  on public.audit_log (actor_id, occurred_at desc);

alter table public.audit_log enable row level security;

revoke all on table public.audit_log from anon, authenticated;
grant select on table public.audit_log to authenticated;

drop policy if exists audit_log_select_admin on public.audit_log;
create policy audit_log_select_admin
on public.audit_log
for select
to authenticated
using (
  (select private.has_any_role(array['ADMIN'::public.user_role]))
);

create or replace function private.write_transport_audit()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  actor uuid := auth.uid();
  actor_role public.user_role;
  old_json jsonb;
  new_json jsonb;
  rid text;
  fields text[];
begin
  if tg_op is null then
    raise exception 'Audit trigger function cannot be called directly.';
  end if;

  if actor is null then
    if tg_op = 'DELETE' then
      return old;
    else
      return new;
    end if;
  end if;

  select p.role
    into actor_role
    from public.profiles p
   where p.id = actor;

  old_json := case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else null end;
  new_json := case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else null end;
  rid := coalesce(new_json ->> 'id', old_json ->> 'id');

  if tg_op = 'INSERT' then
    select coalesce(array_agg(k.key order by k.key), array[]::text[])
      into fields
      from jsonb_object_keys(new_json) as k(key);
  elsif tg_op = 'DELETE' then
    select coalesce(array_agg(k.key order by k.key), array[]::text[])
      into fields
      from jsonb_object_keys(old_json) as k(key);
  else
    select coalesce(array_agg(key order by key), array[]::text[])
      into fields
      from (
        select key
        from (
          select jsonb_object_keys(old_json) as key
          union
          select jsonb_object_keys(new_json) as key
        ) keys
        where (old_json -> key) is distinct from (new_json -> key)
      ) k;
  end if;

  if tg_op <> 'UPDATE' or cardinality(fields) > 0 then
    insert into public.audit_log (
      actor_id,
      actor_role,
      action,
      table_name,
      record_id,
      changed_fields,
      old_data,
      new_data
    )
    values (
      actor,
      actor_role,
      tg_op,
      tg_table_name,
      rid,
      fields,
      old_json,
      new_json
    );
  end if;

  if tg_op = 'DELETE' then
    return old;
  else
    return new;
  end if;
end;
$$;

do $$
declare
  tbl text;
  tables_to_audit text[] := array[
    'profiles',
    'kendaraan',
    'dokumen_kendaraan',
    'permintaan_service',
    'permintaan_service_bukti',
    'service',
    'service_item',
    'service_bukti',
    'service_approval',
    'riwayat_ban',
    'riwayat_aki',
    'riwayat_kilometer',
    'patokan_harga_service',
    'pemilik_sewa',
    'kontrak_sewa',
    'pembayaran_sewa',
    'perbaikan_sewa',
    'potongan_pembayaran_sewa',
    'rental_historis_excel'
  ];
begin
  foreach tbl in array tables_to_audit
  loop
    execute format('drop trigger if exists audit_row_changes on public.%I', tbl);
    execute format(
      'create trigger audit_row_changes after insert or update or delete on public.%I for each row execute function private.write_transport_audit()',
      tbl
    );
  end loop;
end;
$$;
